version: '2'
services:
  casldap:
    domainname: ldap.rd-connect.eu
    hostname: ldap
    image: "rd-connect.eu/cas-ldap:cas-4.1.x"
    volumes:
       - ldap_conf:/etc/openldap
       - ldap_db:/var/lib/ldap
       - ldap_logs:/var/log
  cas:
    depends_on:
       - casldap
    domainname: rdconnectcas.rd-connect.eu
    hostname: rdconnectcas
    image: "rd-connect.eu/rdconnect_cas:cas-4.1.x"
    volumes:
       - cas_conf:/etc/cas
       - tomcat_conf:/etc/tomcat7
       - cas_logs:/var/log
       - pwm_state:/var/lib/pwm
    ports:
       - "9443:9443"
  pla:
    depends_on:
       - casldap
    domainname: rdconnect-pla.rd-connect.eu
    hostname: rdconnect-pla
    image: "rd-connect.eu/phpldapadmin:latest"
    volumes:
       - pla_conf:/etc/phpldapadmin
       - pla_ldap:/etc/openldap
       - pla_pki:/etc/pki/tls
       - pla_logs:/var/log/httpd
    ports:
      - "9444:443"
  umi:
    depends_on:
      - casldap
      - cas
    domainname: rdconnect-umi.rd-connect.eu
    hostname: rdconnect-umi
    image: "rd-connect.eu/rdconnect-umi:latest"
    volumes:
       - umi_conf:/home/rdconnect-rest/RDConnect-UserManagement-REST-API/configs
       - umi_ldap:/etc/openldap
       - umi_pki:/etc/pki/tls
       - umi_logs:/var/log/httpd
    ports:
      - "9445:443"
volumes:
  ldap_conf:
  ldap_db:
  ldap_logs:
  cas_conf:
  tomcat_conf:
  cas_logs:
  pwm_state:
  pla_conf:
  pla_ldap:
  pla_pki:
  pla_logs:
  umi_conf:
  umi_ldap:
  umi_pki:
  umi_logs:
